name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests
        run: mvn test
      - name: Check test results
        if: ${{ failure() }}
        run: echo "Tests failed!"
      - name: Create failure branch
        if: ${{ failure() }}
        run:
          git checkout -b failure-branch-${{ github.run_id }}
          git add .
          git commit -m "Test failure"
          git push --set-upstream origin failure-branch-${{ github.run_id }}
      - name: Git reset
        if: ${{ failure() }}
        run: git reset --hard HEAD@{1}
      - name: Fast forward
        if: ${{ always() }}
        run: git pull --ff-only
